version: "3"
services:
  my5grantester:
    build:
      context: ./
    container_name: my5grantester
    privileged: true
    command: ./app ${TEST_PARAMETERS}
    volumes:
      - ./config/tester.yaml:/workspace/my5G-RANTester/config/config.yml
    cap_add:
      - NET_ADMIN
    networks:
      public_net:
        ipv4_address: 192.168.70.143
      public_net_access:
        ipv4_address: 192.168.72.143

  iperf:
    image: mlabbe/iperf:latest
    container_name: iperf
    ports:
      - 5001:5001
    command: -s
    networks:
      public_net:
        ipv4_address: 192.168.70.144
      public_net_access:
        ipv4_address: 192.168.72.144

networks:
  public_net:
    external:
      name: demo-oai-public-net
  public_net_access:
    external:
      name: oai-public-access
